export const colors = {
	COLOR_PRIMARY: "orange",
	COLOR_LIGHT: "#fff",
	COLOR_DARK: "#000",
	COLOR_DARK_ALT: "#262626",
};

//  Data for categories filter

export const categories = [
	{
		id: "01",
		category: "Breakfast",
	},
	{
		id: "02",
		category: "Lunch",
	},
	{
		id: "03",
		category: "Dinner",
	},
	{
		id: "04",
		category: "Asian",
	},
	{
		id: "05",
		category: "Italian",
	},
	{
		id: "06",
		category: "Desserts",
	},
	{
		id: "07",
		category: "Vegetarian",
	},
	{
		id: "08",
		category: "Seafood",
	},
];

export const recipeList = [
	{
        id: "01",
        name: "French Toast",
        image: require("../assets/images/french_toast.jpeg"),
        rating: "4.4",
        ingredients: ["Bread Slices", "Eggs", "Milk", "Cinnamon", "Vanilla Extract"],
        time: "20 mins",
        difficulty: "Easy",
        calories: "300 cal",
        color: "#9B59B6",
        description: "Golden-brown slices of bread dipped in a mixture of eggs, milk, and spices, served with maple syrup.",
        steps: [
            "In a shallow bowl, whisk together eggs, milk, cinnamon, and vanilla extract.",
            "Dip bread slices into the egg mixture, ensuring both sides are coated.",
            "Cook the bread slices on a greased skillet over medium heat until golden brown on both sides.",
            "Serve hot with maple syrup and your favorite toppings.",
        ],
        categories: ["Breakfast"],
    },
    {
        id: "02",
        name: "Omelette",
        image: require("../assets/images/omelette.jpeg"),
        rating: "4.5",
        ingredients: ["Eggs", "Cheese", "Bell Peppers", "Onions", "Tomatoes", "Mushrooms"],
        time: "15 mins",
        difficulty: "Easy",
        calories: "250 cal",
        color: "#27AE60",
        description: "Fluffy omelette filled with cheese, bell peppers, onions, tomatoes, and mushrooms, a delicious breakfast option.",
        steps: [
            "Beat eggs in a bowl and season with salt and pepper.",
            "Heat a skillet over medium heat and pour in the beaten eggs.",
            "As the eggs begin to set, add grated cheese, chopped bell peppers, onions, tomatoes, and mushrooms.",
            "Fold the omelette in half and cook until the cheese is melted and the eggs are fully cooked.",
            "Serve hot with toast or a side of salad.",
        ],
        categories: ["Breakfast", "Vegetarian"],
    },
    // Add more recipes for the Breakfast category...

    // Lunch category
    {
        id: "03",
        name: "Caprese Salad",
        image: require("../assets/images/caprese_salad.jpeg"),
        rating: "4.6",
        ingredients: ["Tomatoes", "Fresh Mozzarella", "Basil Leaves", "Balsamic Glaze", "Extra Virgin Olive Oil"],
        time: "10 mins",
        difficulty: "Easy",
        calories: "200 cal",
        color: "#E74C3C",
        description: "A refreshing salad made with ripe tomatoes, fresh mozzarella, and fragrant basil leaves, drizzled with balsamic glaze and olive oil.",
        steps: [
            "Slice tomatoes and fresh mozzarella into rounds.",
            "Arrange the tomato and mozzarella slices alternately on a serving plate.",
            "Tuck fresh basil leaves between the tomato and mozzarella slices.",
            "Drizzle with balsamic glaze and extra virgin olive oil.",
            "Season with salt and pepper to taste.",
        ],
        categories: ["Lunch", "Vegetarian"],
    },
    {
        id: "04",
        name: "Quinoa Salad",
        image: require("../assets/images/quinoa_salad.jpeg"),
        rating: "4.3",
        ingredients: ["Quinoa", "Cherry Tomatoes", "Cucumber", "Red Onion", "Feta Cheese", "Lemon Juice", "Olive Oil"],
        time: "25 mins",
        difficulty: "Easy",
        calories: "300 cal",
        color: "#F1C40F",
        description: "A nutritious salad made with cooked quinoa, cherry tomatoes, cucumber, red onion, and crumbled feta cheese, dressed with a lemony vinaigrette.",
        steps: [
            "Cook quinoa according to package instructions and let it cool.",
            "Dice cherry tomatoes, cucumber, and red onion.",
            "In a large bowl, combine cooked quinoa, diced vegetables, and crumbled feta cheese.",
            "Drizzle with lemon juice and olive oil, and toss to coat evenly.",
            "Season with salt and pepper to taste.",
        ],
        categories: ["Lunch", "Vegetarian"],
    },
    // Add more recipes for the Lunch category...

    // Dinner category
    {
        id: "05",
        name: "Spaghetti Carbonara",
        image: require("../assets/images/spaghetti_carbonara.jpeg"),
        rating: "4.7",
        ingredients: ["Spaghetti", "Bacon", "Eggs", "Parmesan Cheese", "Garlic", "Black Pepper"],
        time: "30 mins",
        difficulty: "Medium",
        calories: "400 cal",
        color: "#3498DB",
        description: "A classic Italian pasta dish made with spaghetti, crispy bacon, eggs, Parmesan cheese, and black pepper.",
        steps: [
            "Cook spaghetti according to package instructions until al dente.",
            "In a skillet, cook bacon until crispy, then remove and chop into pieces.",
            "In a bowl, whisk together eggs, grated Parmesan cheese, minced garlic, and black pepper.",
            "Drain cooked spaghetti and immediately add to the egg mixture, tossing to coat evenly.",
            "Add chopped bacon and continue tossing until the sauce thickens.",
            "Serve hot with additional Parmesan cheese and black pepper.",
        ],
        categories: ["Dinner"],
    },
    {
        id: "06",
        name: "Beef Stir-Fry",
        image: require("../assets/images/beef_stir_fry.jpeg"),
        rating: "4.5",
        ingredients: ["Beef Strips", "Bell Peppers", "Broccoli", "Carrots", "Soy Sauce", "Ginger", "Garlic"],
        time: "25 mins",
        difficulty: "Easy",
        calories: "350 cal",
        color: "#8E44AD",
        description: "A quick and flavorful stir-fry dish made with tender beef strips, crunchy bell peppers, broccoli, and carrots, seasoned with soy sauce, ginger, and garlic.",
        steps: [
            "Marinate beef strips in soy sauce, minced ginger, and minced garlic.",
            "Heat oil in a wok or skillet over high heat.",
            "Stir-fry beef until browned, then remove from pan.",
            "Add sliced bell peppers, broccoli florets, and julienned carrots to the pan.",
            "Stir-fry vegetables until tender-crisp.",
            "Return beef to the pan and toss everything together.",
            "Serve hot over cooked rice.",
        ],
        categories: ["Dinner"],
    },
	{
		id: "07",
		name: "Tuna Tartare",
		image: require("../assets/images/tuna.png"),
		rating: "4.2",
		ingredients: ["Fresh Tuna", "Lime Juice", "Red Onion", "Avocado"],
		time: "40 mins",
		difficulty: "Medium",
		calories: "420 cal",
		color: "#006A4E",
		description:
			"A delightful and refreshing dish featuring fresh tuna mixed with zesty lime juice and the crunch of red onion and avocado.",
		steps: [
			"Dice the fresh tuna into small cubes.",
			"Finely chop the red onion and avocado.",
			"Mix the tuna, red onion, and avocado in a bowl.",
			"Drizzle lime juice over the mixture and gently toss.",
			"Serve chilled and enjoy!",
		],
		categories: ["Lunch", "Seafood"], 
	},
	{
		id: "08",
		name: "Lasagna",
		image: require("../assets/images/lasgana.png"),
		rating: "3.6",
		ingredients: [
			"Lasagna Noodles",
			"Ground Beef",
			"Ricotta Cheese",
			"Tomato Sauce",
		],
		time: "40 mins",
		difficulty: "Medium",
		calories: "420 cal",
		color: "#f39c12",
		description:
			"A classic Italian comfort food with layers of lasagna noodles, flavorful ground beef, rich ricotta cheese, and tangy tomato sauce.",
		steps: [
			"Cook the lasagna noodles according to package instructions.",
			"Brown the ground beef in a skillet and season with spices.",
			"Layer the lasagna noodles, beef, ricotta cheese, and tomato sauce in a baking dish.",
			"Repeat the layers and bake in the oven until bubbly and golden.",
			"Let it cool slightly before serving.",
		],
		categories: ["Breakfast", "Seafood"],
	},
	{
		id: "09",
		name: "Hot Dog",
		image: require("../assets/images/hotdog.png"),
		rating: "4.6",
		ingredients: ["Hot Dog Buns", "Frankfurters", "Ketchup", "Mustard"],
		time: "40 mins",
		difficulty: "Medium",
		calories: "420 cal",
		color: "#FF0000",
		// description, steps to prepare
		description:
			"A classic American favorite, hot dog buns stuffed with juicy frankfurters, drizzled with ketchup and mustard for that perfect balance of flavors.",
		steps: [
			"Grill or heat the frankfurters until they're cooked through.",
			"Place the frankfurters in hot dog buns.",
			"Squeeze ketchup and mustard over the frankfurters.",
			"Serve with your favorite sides and enjoy!",
		],
	},
	{
		id: "10",
		name: "Manchurian",
		image: require("../assets/images/manchurian.png"),
		rating: "3.6",
		ingredients: ["Cauliflower", "Soy Sauce", "Ginger", "Garlic"],
		time: "30 mins",
		difficulty: "Easy",
		calories: "350 cal",
		color: "#d35400",
		description:
			"A popular Indo-Chinese dish featuring crispy cauliflower bites tossed in a flavorful sauce made with soy sauce, ginger, and garlic.",
		steps: [
			"Cut the cauliflower into florets and blanch them.",
			"Prepare a sauce by mixing soy sauce, ginger, and garlic.",
			"Deep-fry or shallow-fry the cauliflower until crispy.",
			"Toss the fried cauliflower in the sauce until well coated.",
			"Garnish with chopped green onions and serve hot.",
		],
	},
	{
		id: "11",
		name: "Chicken",
		image: require("../assets/images/chicken.png"),
		rating: "2.2",
		ingredients: ["Chicken Breasts", "Salt", "Black Pepper", "Olive Oil"],
		time: "45 mins",
		difficulty: "Medium",
		calories: "450 cal",
		color: "#8d4004",
		description:
			"A succulent chicken dish seasoned with a blend of salt and black pepper, then cooked to perfection with a drizzle of olive oil.",
		steps: [
			"Preheat the oven to the specified temperature.",
			"Season the chicken breasts with salt and black pepper.",
			"Heat olive oil in a skillet over medium-high heat.",
			"Sear the chicken breasts on both sides until golden brown.",
			"Transfer the chicken to the oven and bake until cooked through.",
			"Serve hot and enjoy your flavorful chicken!",
		],
	},
	{
		id: "12",
		name: "Cupcakes",
		image: require("../assets/images/cupcakes.png"),
		rating: "5.0",
		ingredients: ["Flour", "Sugar", "Eggs", "Butter"],
		time: "60 mins",
		difficulty: "Medium",
		calories: "200 cal",
		description:
			"Delightful cupcakes made with a perfect blend of flour, sugar, eggs, and butter, perfect for any occasion.",
		steps: [
			"Preheat the oven to the specified temperature.",
			"Prepare the cupcake batter by mixing the ingredients together.",
			"Line a muffin tin with cupcake liners.",
			"Fill each liner with batter and bake in the oven.",
			"Let the cupcakes cool, then frost and decorate as desired.",
			"Indulge in these sweet treats and savor the flavor!",
		],
	},
	{
		id: "13",
		name: "Curry",
		image: require("../assets/images/curry.png"),
		rating: "4.8",
		ingredients: ["Meat", "Curry Powder", "Coconut Milk", "Spices"],
		time: "55 mins",
		difficulty: "Hard",
		calories: "550 cal",
		color: "#d35400",

		description:
			"A rich and aromatic curry dish featuring tender pieces of meat cooked in a flavorful blend of curry powder, coconut milk, and spices.",
		steps: [
			"Marinate the meat with spices and let it sit for a while.",
			"Heat oil in a large pot and sauté the marinated meat until browned.",
			"Add curry powder and stir to coat the meat.",
			"Pour in coconut milk and bring to a simmer.",
			"Cover and let the curry simmer until the meat is tender and the flavors meld.",
			"Serve the curry with rice or bread and enjoy the deliciousness!",
		],
	},
	{
		id: "14",
		name: "Ramen",
		image: require("../assets/images/ramen-org.png"),
		rating: "4.2",
		ingredients: ["Ramen Noodles", "Soy Sauce", "Eggs", "Vegetables"],
		time: "35 mins",
		difficulty: "Easy",
		calories: "400 cal",
		color: "#f96163",
		description:
			"A comforting bowl of ramen featuring slurp-worthy noodles, a savory soy sauce-based broth, tender vegetables, and perfectly boiled eggs.",
		steps: [
			"Boil the ramen noodles according to package instructions.",
			"In a pot, bring water to a simmer and add soy sauce for the broth.",
			"Add chopped vegetables and let them cook until tender.",
			"Boil eggs to your desired doneness, then peel and slice them.",
			"Assemble the ramen bowls by placing cooked noodles, vegetables, and egg slices.",
			"Ladle the hot broth over the ingredients and get ready to enjoy your homemade ramen!",
		],
	},
	{
        id: "15",
        name: "Scrambled Eggs",
        image: require("../assets/images/scrambed_eggs.jpg"),
        rating: "4.5",
        ingredients: ["Eggs", "Milk", "Salt", "Pepper"],
        time: "15 mins",
        difficulty: "Easy",
        calories: "200 cal",
        color: "#FFC300",
        description: "Fluffy scrambled eggs cooked to perfection with a dash of milk, salt, and pepper.",
        steps: [
            "Crack the eggs into a bowl and beat them.",
            "Heat a skillet over medium heat and add the beaten eggs.",
            "Stir gently and continuously until the eggs are just set.",
            "Season with salt and pepper to taste.",
            "Serve hot and enjoy!",
        ],
        categories: ["Breakfast", "Vegetarian"],
    },
    {
        id: "16",
        name: "Chicken Caesar Salad",
        image: require("../assets/images/caesar_salad.jpg"),
        rating: "4.3",
        ingredients: ["Romaine Lettuce", "Grilled Chicken", "Caesar Dressing", "Croutons", "Parmesan Cheese"],
        time: "20 mins",
        difficulty: "Easy",
        calories: "350 cal",
        color: "#1ABC9C",
        description: "A classic Caesar salad topped with grilled chicken, crunchy croutons, and grated Parmesan cheese.",
        steps: [
            "Chop the romaine lettuce and place it in a large salad bowl.",
            "Add grilled chicken slices, croutons, and grated Parmesan cheese.",
            "Drizzle Caesar dressing over the salad and toss to coat evenly.",
            "Serve immediately as a light and refreshing meal.",
        ],
        categories: ["Lunch"],
    },
];
